### PR TITLE
Fixes for making it work on Go 1.7

### PR DESCRIPTION
**Pull request by mvader**

### CODE REVIEW

**Comment by mcuadros** [comment]
update travis plz

**Comment by mvader** [comment]
@mcuadros done

**Comment by alcortesm** [comment]
LGTM

**Comment by mvader** [comment]
Thing is, I can't make the travis pull request work. It throws status code 1 while making `go get`. Specifically when downloading `github.com/jessevdk/go-flags`.

**Comment by mvader** [comment]
yay, made it work on travis. Turns out we were using go-uuid to generate random database names and that dependency is no longer available, that's why it failed

PTAL @mcuadros

**Pull request merged**
